// packages/website/components/ContactForm.vue
<template>
  <form
    v-if="!hasSubmitted"
    :name="formName"
    data-netlify="true"
    class="grid gap-4 md:grid-cols-2"
    @submit.prevent="handleSubmit"
  >
    <!-- We need this for Netlify's forms. -->
    <input type="hidden" name="form-name" :value="formName" />
    <UiFormField
      v-for="(field, index) in formFields"
      :key="index"
      :label="field.label"
      label-position="top"
      :required="true"
      :class="field.class"
      :error="v$[field.model].$errors[0]?.$message ?? null"
    >
      <component
        :is="field.component"
        v-model="formData[field.model]"
        input-class="form-input"
        :name="field.model"
        :placeholder="field.placeholder"
        :required="!!rules[field.model].required"
      />
    </UiFormField>
    <small class="col-span-full font-bold text-black">An asterisk (*) means that the field is required.</small>
    <div class="mt-4 flex justify-center md:col-span-2">
      <UiButton color="secondary" type="submit">
        Submit
      </UiButton>
    </div>
  </form>
  <div v-else>
    <div class="text-center text-2xl font-bold text-white">
      Thanks for reaching out!
    </div>
    <div class="text-center text-xl text-white">
      I'll get back to you as soon as possible.
    </div>
  </div>
</template>

<script lang="ts" setup>
import { reactive } from 'vue'
import type { Component } from 'vue'
import { useVuelidate } from '@vuelidate/core'
import { required, email, helpers } from '@vuelidate/validators'
import UiTextInput from './ui/TextInput/TextInput.vue'
import UiTextareaInput from './ui/TextareaInput/TextareaInput.vue'

interface FormData {
  name: string;
  email: string;
  message: string;
}

interface FormField {
  label: string;
  model: string;
  component: Component;
  placeholder: string;
  class?: string;
}

const emit = defineEmits<{(event: 'submit', value: FormData): void}>()

const hasSubmitted = ref(false)
const formData = reactive<FormData>({ name: '', email: '', message: '' })
const rules = reactive({
  name: { required: helpers.withMessage('Name is required', required) },
  email: {
    required: helpers.withMessage('Email is required', required),
    email: helpers.withMessage('Email must be valid', email),
  },
  message: { required: helpers.withMessage('Message is required', required) },
})

const v$ = useVuelidate(rules, formData)

const formName = 'contact-form'
const formFields: FormField[] = [
  { label: 'Your Name', model: 'name', component: UiTextInput, placeholder: 'Jack' },
  { label: 'Your Email', model: 'email', component: UiTextInput, placeholder: 'Sparrow' },
  { label: 'Your Message', model: 'message', component: UiTextareaInput, placeholder: 'Why is the rum always gone?', class: 'md:col-span-2' },
]

const handleSubmit = () => {
  v$.value.$touch()

  if (v$.value.$error) {
    return
  }

  const formKeyValues = Object.entries(formData)
  // const newFormData = new FormData()
  // formKeyValues.forEach(([key, value]) => newFormData.append(key, value))

  const urlEncodedFormData = new URLSearchParams(formKeyValues)
  urlEncodedFormData.append('form-name', 'contact-form')

  fetch('/', {
    method: 'POST',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
    body: urlEncodedFormData.toString(),
  })
    .then(() => {
      hasSubmitted.value = true
      emit('submit', formData)
    },
    (error) => {
      console.error(error)
    })
}

</script>

// apps/portfolio/src/components/ContactForm.tsx
import { z } from 'zod';
import {
  ValidatedForm,
  Field,
  TextInput,
  TextareaInput,
  CheckboxField,
} from '@bracketbear/core/react';
import { ParticleButton } from '@/components/ParticleButton';

const contactSchema = z.object({
  name: z.string().min(2, 'Name is required'),
  email: z.string().email('Valid email required'),
  message: z.string().min(10, 'Message must be at least 10 characters'),
  resume: z.boolean().optional(),
});

type ContactFormValues = z.infer<typeof contactSchema>;

export function ContactForm() {
  const handleSubmit = async (values: ContactFormValues) => {
    try {
      // Create URLSearchParams for Netlify submission
      const formData = new URLSearchParams();
      formData.append('form-name', 'contact');
      formData.append('name', values.name);
      formData.append('email', values.email);
      formData.append('message', values.message);
      if (values.resume) {
        formData.append('resume', 'true');
      }

      // Submit to Netlify Forms endpoint
      const response = await fetch('/', {
        method: 'POST',
        headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
        body: formData.toString(),
      });

      if (!response.ok) {
        throw new Error('Failed to submit form');
      }
    } catch {
      throw new Error('Failed to send message. Please try again.');
    }
  };

  return (
    <ValidatedForm
      schema={contactSchema}
      onSubmit={handleSubmit}
      animateOnSuccess
      animateOnError
      className="brutalist-form rounded-lg"
      aria-label="Contact form"
    >
      {({
        values,
        errors,
        handleChange,
        handleBlur,
        isSubmitting,
        submitError,
        submitSuccess,
      }) => (
        <>
          {/* Hidden form for Netlify to detect */}
          <form name="contact" method="POST" data-netlify="true" hidden>
            <input type="text" name="name" />
            <input type="email" name="email" />
            <textarea name="message"></textarea>
            <input type="checkbox" name="resume" />
          </form>

          <div className="mb-6 grid gap-2">
            <Field label="Name" id="name" error={errors.name} required>
              <TextInput
                id="name"
                name="name"
                value={values.name || ''}
                onChange={handleChange}
                onBlur={handleBlur}
                disabled={isSubmitting}
                autoComplete="name"
                error={errors.name}
                aria-required="true"
                aria-invalid={errors.name ? 'true' : 'false'}
                aria-describedby={errors.name ? 'name-error' : undefined}
              />
            </Field>
            <Field label="Email" id="email" error={errors.email} required>
              <TextInput
                id="email"
                name="email"
                type="email"
                value={values.email || ''}
                onChange={handleChange}
                onBlur={handleBlur}
                disabled={isSubmitting}
                autoComplete="email"
                error={errors.email}
                aria-required="true"
                aria-invalid={errors.email ? 'true' : 'false'}
                aria-describedby={errors.email ? 'email-error' : undefined}
              />
            </Field>
            <Field label="Message" id="message" error={errors.message} required>
              <TextareaInput
                id="message"
                name="message"
                rows={6}
                value={values.message || ''}
                onChange={handleChange}
                onBlur={handleBlur}
                disabled={isSubmitting}
                error={errors.message}
                aria-required="true"
                aria-invalid={errors.message ? 'true' : 'false'}
                aria-describedby={errors.message ? 'message-error' : undefined}
              />
            </Field>
            <CheckboxField
              id="resume"
              name="resume"
              checked={!!values.resume}
              onChange={handleChange}
              disabled={isSubmitting}
              label="Request my resume"
              error={errors.resume}
            />
          </div>
          <div className="flex flex-col items-center gap-4">
            <ParticleButton
              type="submit"
              className="px-8 py-4 text-xl"
              particleCount={50}
              particleSize={6}
              particleSpeed={2}
              disabled={isSubmitting}
              aria-label={isSubmitting ? 'Sending message...' : 'Send message'}
            >
              {isSubmitting ? 'Sending…' : 'Send Message'}
            </ParticleButton>
            {submitError && (
              <div
                className="animate-shake text-secondary mt-2 font-bold"
                role="alert"
                aria-live="polite"
              >
                {submitError}
              </div>
            )}
            {submitSuccess && (
              <div
                className="animate-pop text-muted mt-2 font-bold"
                role="status"
                aria-live="polite"
              >
                Message sent! I'll get back to you soon.
              </div>
            )}
          </div>
        </>
      )}
    </ValidatedForm>
  );
}
